### PR TITLE
Update class-tooltip-parser.php

### PR DESCRIPTION
**Pull request by naofireblade**
Limit characters in definition at the last whitespace before the given limit is reached. Prevents words from being cut in the middle.

### CODE REVIEW

**Comment by chorton2227** [comment]
This is a good idea. I think we should also be preventing extra whitespace and punctuation characters, since it's adding `...` to the end of the definition.

**Comment by naofireblade** [comment]
Done. But had some problems with multiple whitespaces converted to &nbsp; by htmlspecialchars()

**Comment by chorton2227** [comment]
Yes, there are problems when trying to append the html to the DomDocument as xml. See [here](https://github.com/naofireblade/WP-Glossary-Hover/blob/e37060825108ca0d5361ba16768cf694542034f2/public/includes/class-tooltip-parser.php#L222).

And I'm working on a fix.

**Comment by chorton2227** [comment]
Changes merged in [1.2.1 branch](https://github.com/chorton2227/WP-Glossary-Hover/tree/90d97248f0f645f16bf53b72c2d32d2a6b1dbd68)

**Pull request closed without merging**
